# Generated by Django 5.0.1 on 2024-01-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20240130_0720'),
    ]

    operations = [
    ]
